apiVersion: v1
kind: List
items:
-
    apiVersion: apps/v1
    kind: Deployment    
    metadata:
      name: pgadmin-app
      labels:
        app: pgadmin-app
        app.kubernetes.io/part-of: pgadmin-app      
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: pgadmin-app
      template:
        metadata:
          labels:
            app: pgadmin-app
          annotations:
        spec:
          volumes:
            - name: pga-storage
              persistentVolumeClaim:
                claimName: pgadmin-storage
          containers:
            - resources: {}
              name: pgadmin-app
              env:
                - name: PGADMIN_DEFAULT_EMAIL
                  value: v6tempest@yahoo.com
                - name: PGADMIN_DEFAULT_PASSWORD
                  value: password 
              ports:
                - containerPort: 8080
              volumeMounts:
                - name: pga-storage
                  mountPath: /var/lib/pgadmin   
              image: quay.io/bitnami/postgresql
              imagePullPolicy: Always          
        
-   kind: Service
    apiVersion: v1
    metadata:
      name: pgadmin-app
      labels:
        app: pgadmin-app   
    spec:
      ports:
      - port: 8080
        targetPort: 8080
      selector:
        app: pgadmin-app
                 
