apiVersion: v1
kind: List
items:
-
    apiVersion: apps/v1
    kind: Deployment    
    metadata:
      name: pgadmin-app
      labels:
        app: pgadmin-app
        app.kubernetes.io/part-of: pgadmin-app      
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: pgadmin-app
      template:
        metadata:
          labels:
            app: pgadmin-app
          annotations:
        spec:
          volumes:
            - name: pga-storage
              persistentVolumeClaim:
                claimName: pgadmin-storage
          containers:
            - resources: {}
              name: pgadmin-app
              env:
                - name: PGADMIN_DEFAULT_EMAIL
                  value: v6tempest@yahoo.com
                - name: PGADMIN_DEFAULT_PASSWORD
                  value: password 
              ports:
                - containerPort: 80
                  protocol: TCP
                - containerPort: 443
                  protocol: TCP
              volumeMounts:
                - name: pga-storage
                  mountPath: /var/lib/pgadmin   
              image: quay.io/v6tempest1/dbadmin-tool:latest
              imagePullPolicy: Always          
        
- kind: Service
  apiVersion: v1
  metadata:
    name: pgadmin-app
    labels:
      app: pgadmin-app   
  spec:
    ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
    - name: 443-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    selector:
      app: pgadmin-app

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pgadmin-storage
  spec:
    accessModes:
     - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
                 
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    labels:
      app: pgadmin-app
    name: pgadmin-route
  spec:
    to:
      kind: Service
      name: pgadmin-app
    ports:
    - port: 80
      targetPort: 80