apiVersion: v1
kind: List
items:
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: postgresql
    name: postgresql
  spec:
    selector:
      matchLabels:
        name: postgresql
    template:
      metadata:
        labels:
          name: postgresql
        name: postgresql
      spec:
        containers:
        - image: quay.io/bitnami/postgresql
          name: postgresql
          ports:
          - name: postgresql
            containerPort: 5432   
        
-
  apiVersion: v1
  kind: Service
  metadata:
    name: postgresql
    labels:
      name: postgresql
  spec:
    ports:
      - port: 5432
        targetPort: 5432
    selector:
      name: postgresql
