apiVersion: v1
kind: List
items:
-
    apiVersion: v1
    kind: Deployment    
    metadata:
      name: postgresql
    labels:
        app: postgresql
        app.kubernetes.io/part-of: postgresql      
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgresql
      template:
        metadata:
          name: postgresql
          labels:
            app: postgresql
          annotations:
        spec:
          containers:
          - env:
              - name: POSTGRES_USER
                value: postgres
              - name: POSTGRES_PASSWORD
                value: password
              - name: POSTGRES_DB
                value: student
            image: quay.io/bitnami/postgresql
            imagePullPolicy: Always
            name: postgresql
            ports:
            - containerPort: 5432
              
-   kind: Service
    apiVersion: v1
    metadata:
      name: postgresql
      labels:
        app: postgresql    
    spec:
      ports:
      - port: 5432
        targetPort: 5432
      selector:
        app: postgresql

