apiVersion: v1
kind: List
items:
-
    apiVersion: v1
-   kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: postgresql
    labels:
        app: postgresql
        app.kubernetes.io/part-of: postgresql      
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgresql
      template:
        metadata:
          name: postgresql
          labels:
            app: postgresql
          annotations:
        spec:
          containers:
          - env:
            image: postgresql:latest
            imagePullPolicy: Always
            name: postgresql
            ports:
            - containerPort: 5432
              
-   kind: Service
    apiVersion: v1
    metadata:
      name: postgresql
      labels:
        app: postgresql    
    spec:
      ports:
      - port: 5432
        targetPort: 5432
      selector:
        app: postgresql

