apiVersion: v1
kind: List
items:
-
    apiVersion: v1
-   kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: postgresql
        app.kubernetes.io/part-of: postgresql
      name: postgresql
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgresql
      template:
        metadata:
          name: postgresql
          labels:
            app: postgresql
          annotations:
        spec:
          containers:
          - env:
            image: image-registry.openshift-image-registry.svc:5000/marcos-serranojr-dev/postgresql@sha256:f6c627897d423659fac04f99bfa4c938c781a34eb3157832f046b89065e6ebc0
            imagePullPolicy: Always
            name: postgresql
            ports:
            - containerPort: 5432
              name: http
              protocol: TCP 
-   kind: Service
    apiVersion: v1
    metadata:
      name: postgresql
      labels:
        app: postgresql    
    spec:
      ports:
      - name: http
        port: 5432
      selector:
        app: postgresql
-   kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: postgresql
      name: postgresql-route
    spec:
      to:
        kind: Service
