apiVersion: v1
kind: List
items:
-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      name: postgresql
    name: postgresql
  spec:
    selector:
      matchLabels:
        name: postgresql
    template:
      metadata:
        labels:
          name: postgresql
        name: postgresql
      spec:
        containers:
        - image: image-registry.openshift-image-registry.svc:5000/studentdemo/postgresql@sha256:f6c627897d423659fac04f99bfa4c938c781a34eb3157832f046b89065e6ebc0
          name: postgresql
          ports:
          - name: postgresql
            containerPort: 5432
          volumeMounts:
              - name: postgresql-1
             	mountPath: /bitnami/postgresql
              - name: postgresql-2
                mountPath: /docker-entrypoint-initdb.d
              - name: postgresql-3
                mountPath: /docker-entrypoint-preinitdb.d
        
-
  apiVersion: v1
  kind: Service
  metadata:
    name: postgresql
    labels:
      name: postgresql
  spec:
    ports:
      - port: 5432
        targetPort: 5432
    selector:
      name: postgresql
