apiVersion: v1
kind: List
items:
-
    apiVersion: v1
    kind: Deployment
    metadata:
        name: postgresql
        labels:
            app: postgresql
    spec:
        template:
        metadata:
            name: postgresql
            app:
                name: postgresql
        spec:
            containers:
            - image:  image-registry.openshift-image-registry.svc:5000/marcos-serranojr-dev/postgresql@sha256:f6c627897d423659fac04f99bfa4c938c781a34eb3157832f046b89065e6ebc0
              name: postgresql
              ports:
              - name: postgresql
                containerPort: 5432
                volumeMounts:
                - name: pg-storage
                  mountPath: /var/lib/postgresql/data
            volumes:
            - name: pg-storage
              persistentVolumeClaim:
                  claimName: pg-storage
-
    apiVersion: v1
    kind: Service
    metadata:
        name: postgresql
        labels:
            app: postgresql
            name: postgresql
    spec:                                                            
        ports:
            - port: 5432
              targetPort: 5432
        selector:
            app: postgresql
-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
        name: pg-storage
        labels:
        app: postgresql
    spec:
        accessModes:
         - ReadWriteOnce
        resources:
            requests:
                storage: 1Gi
